// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3glybo4r6A0RBAXU-vhahg0iRCMDe2w8',
    appId: '1:976542714348:web:a69836536371d13fad18c9',
    messagingSenderId: '976542714348',
    projectId: 'accident-b76e0',
    authDomain: 'accident-b76e0.firebaseapp.com',
    storageBucket: 'accident-b76e0.firebasestorage.app',
    measurementId: 'G-SM49P0DYMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi_QOe0LiUQ1BFUUTpwi6hAzwT5WP1Cmk',
    appId: '1:976542714348:android:ba1abc7493d0cf60ad18c9',
    messagingSenderId: '976542714348',
    projectId: 'accident-b76e0',
    storageBucket: 'accident-b76e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbKjqWDr5WHAvDRLntAaAl1-C4xJPildI',
    appId: '1:976542714348:ios:86f8fae9908ffea0ad18c9',
    messagingSenderId: '976542714348',
    projectId: 'accident-b76e0',
    storageBucket: 'accident-b76e0.firebasestorage.app',
    iosBundleId: 'com.example.accidentAdmin',
  );

}